### ISSUE TITLE
rspec_api_documentation + raddocs

### ISSUE THREAD

**Issue by zharikovpro** [zharikovpro/railgun#132]
https://github.com/zipmark/rspec_api_documentation

https://www.slideshare.net/cyberd0nkey/building-better-ap-is-on-rails

**Comment by Mifrill** [comment]
https://github.com/zipmark/rspec_api_documentation/issues/341

**Comment by zharikovpro** [comment]
Looks like issue with request spec, not rspec_api_documentation gem.

**Comment by Mifrill** [comment]
I think that your config that you did for spec and paperclip so that the files were not downloaded to the server during the tests does not allow you to download files in these caches, everything else works and you can merge

**Comment by zharikovpro** [comment]
Here is *the fact*.

When I run `bundle exec rspec` for that branch, I have same errors:

1) Medias POST /api/v1/medias Create media
     Failure/Error: expect(JSON.parse(response_body)).to eq('avatar')
     
       expected: "avatar"
            got: {"file_file_name"=>["can't be blank"]}
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -"avatar"
       +"file_file_name" => ["can't be blank"],
       
     # ./spec/acceptance/medias_spec.rb:53:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:30:in `block (2 levels) in <top (required)>'

                                                                                                                                                                      
  2) Medias PUT /api/v1/medias/:id Update media
     Failure/Error: expect(Media.find_by_slug(:about).file_file_name).to eq('README.md')
     
       expected: "README.md"
            got: "demo.jpg"
     
       (compared using ==)
     # ./spec/acceptance/medias_spec.rb:70:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:30:in `block (2 levels) in <top (required)>'


Branch with failed specs cannot be merged.
