### ISSUE TITLE
GraphQL: create media file

### ISSUE THREAD

**Issue by zharikovpro** [zharikovpro/railgun#171]

**Comment by Mifrill** [comment]
Aws::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

**Comment by zharikovpro** [comment]
You should check if you can upload file from admin area, or using regular API.

**Comment by zharikovpro** [comment]
That way you will find out whether credentials are outdated or not.

**Comment by Mifrill** [comment]
This is exactly the error when loading through the admin panel and regular api, in the tests everything works

https://monosnap.com/file/kECy1sXzZLag2mYOKUCwcYYyiotU1z

**Comment by zharikovpro** [comment]
Admin area work in production with correct credentials. You don't know them, of course. When testing locally, you shouldn't upload to AWS. Make a fake/store files locally, etc. Production keys are fine. There's no dev keys on purpose.

**Comment by zharikovpro** [comment]
> in the tests everything works

You should develop new feature same way - with tests. Tests do not hit AWS server with real credentials.
