### ISSUE TITLE
are there  reasons to adding configure other CI servers ?

### ISSUE THREAD

**Issue by Mifrill** [zharikovpro/railgun#200]
For example [official ruby repo](https://github.com/ruby/ruby) used 2 CI servers
We can connect one of these servers for additional checks, or all of them:

[Travis](https://travis-ci.org/)
[AppVeyor](https://ci.appveyor.com)
[CodeShip](https://codeship.com/)
[SolanoLabs](https://www.solanolabs.com/)
[CircleCI 2.0](https://circleci.com/)

I thinking about this, because sometimes the tests pass locally, but on the server tests are fail, this can help to find the cause faster and fix it.

In addition, for example, appveyor uses Windows as the main OC, which means that you can position the application as a cross-platform application, and use the config file for deployed on any Paas or VDS

**Comment by zharikovpro** [comment]
> are there reasons to adding configure other CI servers

I'm aware about only one reason - if one server fails, another could work.

> because sometimes the tests pass locally, but on the server tests are fail, this can help to find the cause faster and fix it.

I don't understand: how another server will help in this case if one is not enough?

> appveyor uses Windows

It's a bad idea to deploy RoR on WIndows. No benefits at all, only pain. Thus, no benefits here.

**Comment by zharikovpro** [comment]
Closed via #202
