### ISSUE TITLE
Required ruby-2.4.1 is not installed. To install do: 'rvm install "ruby-2.4.1"'

### ISSUE THREAD

**Issue by stealwin** [zharikovpro/railgun#232]
I have a version ruby 2.4.2. How i can run project on my Ruby, is it possible?

**Comment by zharikovpro** [comment]
Sure yes, you can put the desired version in `.ruby-version`. 

2.4.1 is the supported minimum, newer versions will work just fine.

**Comment by Mifrill** [comment]
@stealwin  Is there any reason to leave this issue unresolved?
If you have any problems with the installation, please write about them, we will help you solve them. If everything works without errors, please do not keep the issue open. Thank you

**Comment by zharikovpro** [comment]
@Mifrill yup, will close as this thread already has a solution, thanks.
