### ISSUE TITLE
use test-reporter against ruby-test-reporter

### ISSUE THREAD

**Issue by Mifrill** [zharikovpro/railgun#235]
Reasons: Update to latest simplecov
https://github.com/codeclimate/ruby-test-reporter/issues/188

**Comment by zharikovpro** [comment]
@Mifrill 

ruby-test-reporter has 1 open issue (Heroku CI support, opened by me) VS test-reporter has 30 open issues.

I see no issues with current versions of ruby-test-reporter and simplecov. So, updating simplecov will force to use ruby-test-reporter with more issues. Other than seeing new version signature in Gemfile, I see no real benefits in that upgrade. So, this is again bleeding edge VS stability issue.

**Comment by zharikovpro** [comment]
@Mifrill do you have a specific use case that requires such upgrade?

**Comment by Mifrill** [comment]
@zharikovpro , Yup
>  These configuration instructions refer to a language-specific test reporter that will soon be deprecated in favor of our new unified test reporter client. The new test reporter is faster, distributed as a static binary, has support for parallelized CI builds, and will receive ongoing support by the team here. The existing test reporters for Ruby, Python, PHP, and Javascript are not yet deprecated but they're unofficially in maintenance mode.

in any case, in the future will have to do it, because
> they're unofficially in maintenance mode. (about test reporters)

 - we do not support gem
 - when using other languages, we can use the same reporter
 - except change of travis config file, this will not affect the project

**Comment by zharikovpro** [comment]
Okay, I will leave this issue open. When ruby-test-reported will be deprecated officially, it will be a great time to switch - to get support, etc. I also expect CodeClimate to fix most of the issues before this switch, as usually happens.

**Comment by Mifrill** [comment]
https://github.com/codeclimate/ruby-test-reporter/commit/8066a8f0d59b53289683584a33c7bc6a517a1d7e
it seems that now it is relevant

**Comment by Mifrill** [comment]
@zharikovpro 
> I will leave this issue open. When ruby-test-reported will be deprecated officially, it will be a great time to switch
https://github.com/zharikovpro/railgun/issues/235#issuecomment-357506866

codeclimate-test-reporter officially deprecated now, let's merge it
https://github.com/codeclimate/ruby-test-reporter#codeclimate-test-reporter---deprecated
